import { getNetworkConfig } from '@ika.xyz/sdk';
import { getFullnodeUrl } from '@mysten/sui/client';

export type Network = 'localnet' | 'testnet' | 'mainnet';

// ReturnType<typeof getNetworkConfig> — IkaNetworkConfig is NOT a named export.
export type IkaConfig = ReturnType<typeof getNetworkConfig>;

// Working RPC endpoints — the default Sui testnet RPC aggressively rate-limits the
// SDK's multi-call patterns (fetchAllDynamicFields etc.) and returns 429.
// publicnode tolerates the SDK's burst patterns.
const RPC_URLS: Record<Network, string> = {
  localnet: 'http://127.0.0.1:9000',
  testnet: 'https://sui-testnet-rpc.publicnode.com',
  mainnet: 'https://ikafn-on-sui-2-mainnet.ika-network.net/',
};

export interface AppConfig {
  network: Network;
  rpcUrl: string;
  ika: IkaConfig;
}

export function buildConfig(): AppConfig {
  const network = (process.env.NETWORK ?? 'testnet') as Network;
  const rpcUrl = process.env.RPC_URL ?? RPC_URLS[network];

  if (network === 'localnet') {
    // Localnet requires ika_config.json generated by the local node.
    // getNetworkConfig() only covers testnet/mainnet.
    // See: https://github.com/dwallet-labs/ika/tree/main/examples/keyspring
    throw new Error(
      'Localnet config must be loaded from ika_config.json. ' +
        'See: https://github.com/dwallet-labs/ika/tree/main/examples/keyspring'
    );
  }

  return {
    network,
    rpcUrl,
    ika: getNetworkConfig(network),
  };
}
